name: und1_mobile
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0-122.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.0.0
  flutter_slidable: ^1.3.0
  flutter_svg: ^2.0.7
  provider: ^6.0.5
  firebase_core: ^2.20.0
  cloud_firestore: ^4.12.1
  firebase_auth: ^4.12.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.4
  firebase_storage: ^11.5.3
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/filme.jpg
    - assets/serie.jpg
    - assets/movie-symbol.png
    - assets/clapper.png
